language: cpp
compiler: gcc

sudo: false

env:
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

before_install:
  - apt-get update
  - apt-get install -y git-core make cmake gcc g++ libmad0-dev libsndfile1-dev libgd2-xpm-dev libboost-filesystem-dev libboost-program-options-dev libboost-regex-dev
  - wget https://googlemock.googlecode.com/files/gmock-1.7.0.zip && unzip gmock-1.7.0.zip && mv gmock-1.7.0 gmock

before_script:
  - mkdir build && cd build
  - cmake -D CMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - make

script:
  - make test
  - ./audiowaveform_tests
